# Generated by Django 3.2.7 on 2021-10-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('doc_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('type_doc', models.CharField(choices=[('CC', 'Cedula'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte')], max_length=4)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
